[package]
name = "schematools"
description = "Tools for codegen, preprocessing and validation of json-schema and openapi spec"
version = "0.6.0"
authors = ["Kacper Stasik <kacper@stasik.eu>"]
edition = "2018"

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9.14"
url = "2"
lazy_static = "1.4.0"
regex = "1"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
jsonschema = { version = "0.14", default-features = false, features = ["reqwest", "reqwest-rustls-tls"] }
reqwest = { version = "0.11.12", default-features = false, features = ["blocking"] }
tera = { version = "1", default-features = false }
serde = { version = "1.0", features = ["derive"] }
walkdir = "2"
json-patch = "=0.2.6"
semver = "0.11.0"
git2 = "0.15.0"
md5 = "0.7.0"
Inflector = "*"
sha2 = "0.10.1"
digest = "0.10.1"

[dev-dependencies]
test-case = "2.2.2"
testing_logger = "0.1.1"
