on:
  pull_request: {}
  push:
    branches:
      - rebuild

name: build

jobs:
  build_unix:
    name: Build for unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: cargo install --path .